### ISSUE TITLE
Procedures are not removed from the registry upon completion

### ISSUE THREAD

**Issue by okkero** [brian-watkins/elm-procedure#21]
Hey. I was testing this out and noticed that procedures do not get removed from the registry when they complete. I went through the commit history and noticed that it used to work like that before, but it was changed at some point.

Is this a bug? Seems like it could cause memory problems.

**Comment by brian-watkins** [comment]
I think you could be right ... In cases where a channel is joined or opened as part of a procedure, some information is stored and not cleaned up if that procedure completes. There is a way to fix this -- basically, the information could be deleted once the procedure has no more open channels -- but I'd like to think about it for a bit to make sure there are no downsides. I'll try to provide a fix within the next few days. 

Thanks for pointing this out!

**Comment by okkero** [comment]
Thank you for taking the time.

**Comment by brian-watkins** [comment]
Just released version 1.1.1 of elm-procedure with a fix for this. Thanks again for reaching out!
